[package]
name = "fortuna"
version = "0.1.0"
authors = ["Garren Smith <garren.smith@gmail.com>"]
edition = "2018"
license = "Apache 2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_v8 = "0.4.2"
prost = "0.6.1"
tonic = "0.1.1"
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
futures-util = "0.3.4"
crossbeam = "0.7.3"
reqwest = "0.10.4"
futures = "0.3.4"
log = "0.4"
pretty_env_logger = "0.4.0"

[build-dependencies]
tonic-build = "0.1.1"

[[bin]]
name = "client"
path = "src/client.rs"

